### ISSUE TITLE
[Feature Request] Donations

### ISSUE THREAD

**Issue by realjoshharrison** [MarkEdit-app/MarkEdit#800]
Hi! Thanks for all your work on this brilliant, helpful app. Is there any way to donate to show appreciation?

**Comment by cyanzhong** [comment]
I really appreciate your kindness, and I believe this is the best form of appreciation. However, as I mentioned in the README, I created this project because I needed it myself—giving back to the open-source community was just a secondary goal. I don't rely on this project for a living.

You don't need to worry about its future—it doesn't take up much of my time, so I plan to maintain it for the foreseeable future. That said, please don't set your expectations too high; this is, first and foremost, a project designed to meet my own needs.
